// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webhooks_System_Library.Entities;

public partial class WebhookEp
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Url { get; set; }

    public string Secret { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<WebhookEvent> WebhookEvents { get; set; } = new List<WebhookEvent>();
}