// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Webhooks_System_Library.Entities;

public partial class WebhookEvent
{
    public int Id { get; set; }

    public int EventPointId { get; set; }

    public string EventType { get; set; }

    public string Payload { get; set; }

    public WebHookStatus Status { get; set; }

    public short AttemptCount { get; set; }

    public DateTime? NextAttemptAt { get; set; }

    public DateTime? LastAttemptAt { get; set; }

    public int? LastResponsecode { get; set; }

    public string LastErrorMessage { get; set; }

    public DateTime? ProcessingLockUntil { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? DeliveredAt { get; set; }

    public virtual WebhookEp EventPoint { get; set; }
}