// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Webhooks_System_Library.Entities;

namespace Webhooks_System_Library.Data;

public partial class WebhooksDeliveryContext : DbContext
{
    public WebhooksDeliveryContext(DbContextOptions<WebhooksDeliveryContext> options)
        : base(options)
    {
    }

    public virtual DbSet<WebhookEp> WebhookEps { get; set; }

    public virtual DbSet<WebhookEvent> WebhookEvents { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<WebhookEp>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WebhookE__3213E83F9E4B3C7F");

            entity.ToTable("WebhookEPs");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getutcdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsActive).HasDefaultValue(true);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.Secret)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(500);
        });

        modelBuilder.Entity<WebhookEvent>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__WebhookE__3213E83F6480D90B");

            entity.HasIndex(e => new { e.Status, e.NextAttemptAt }, "ix_events_pending").HasFilter("([Status]=(0))");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
            entity.Property(e => e.EventPointId).HasColumnName("EventPointID");
            entity.Property(e => e.EventType)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.LastErrorMessage).HasMaxLength(500);
            entity.Property(e => e.Payload).IsRequired();

            entity.HasOne(d => d.EventPoint).WithMany(p => p.WebhookEvents)
                .HasForeignKey(d => d.EventPointId)
                .HasConstraintName("fk_webhookEPs_to_webhookEvents");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}